#!/usr/bin/env python3
"""Validate a bundle generated by chatgpt_to_okf without third-party packages."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("bundle", type=Path)
    args = parser.parse_args()
    bundle = args.bundle
    manifest_path = bundle / "manifest.json"
    if not (bundle / "index.md").is_file() or not manifest_path.is_file():
        print("invalid: bundle must contain index.md and manifest.json", file=sys.stderr)
        return 2
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    entries = manifest.get("entries")
    if not isinstance(entries, list) or manifest.get("memory_count") != len(entries):
        print("invalid: manifest memory_count and entries disagree", file=sys.stderr)
        return 2
    failures: list[str] = []
    seen: set[str] = set()
    for entry in entries:
        if not isinstance(entry, dict):
            failures.append("manifest contains a non-object entry")
            continue
        source_id = entry.get("source_id")
        relative = entry.get("path")
        if not isinstance(source_id, str) or source_id in seen:
            failures.append(f"invalid or duplicate source_id: {source_id!r}")
            continue
        seen.add(source_id)
        if not isinstance(relative, str):
            failures.append(f"entry {source_id} has no path")
            continue
        file_path = bundle / relative
        try:
            file_path.resolve().relative_to(bundle.resolve())
        except ValueError:
            failures.append(f"entry {source_id} escapes bundle root")
            continue
        if not file_path.is_file():
            failures.append(f"missing document for {source_id}")
            continue
        text = file_path.read_text(encoding="utf-8")
        if not text.startswith("---\n") or "\ntype: event\n" not in text:
            failures.append(f"document is not an event OKF node: {relative}")
        if entry.get("document_sha256") != digest(file_path):
            failures.append(f"checksum mismatch: {relative}")
    report = {
        "valid": not failures,
        "memory_count": len(entries),
        "redacted": manifest.get("redacted"),
        "failures": failures,
    }
    print(json.dumps(report, indent=2))
    return 0 if not failures else 2


if __name__ == "__main__":
    raise SystemExit(main())
