"""Write mapped memories as provider-style JSON for ``memanto migrate --file``.

This is the adapter's *secondary* output. The CLI has no ``graphiti`` provider,
so this file is emitted in the shape ``memanto migrate mem0 --file`` accepts.
Two things are worth being blunt about, because they are the reason the OKF
bundle -- not this file -- is the recommended import path:

* ``map_mem0`` hard-codes ``source="mem0"`` and ``confidence=0.8``, so the
  Graphiti provenance and the temporal-standing confidence computed in
  :mod:`graphiti_okf.mapping` are both lost on this path.
* The savings report the CLI renders from it is Mem0-branded, because that is
  the comparison module wired to this provider.

Nothing is *fabricated* by using it -- every number the report computes is
derived from the real Graphiti content -- but the labelling is borrowed. The
file therefore carries an explicit ``_adapter`` provenance block so it can
never be mistaken for a genuine Mem0 account export.

The type still survives: ``map_mem0`` resolves a memory's type from its first
category, falling back to any string that is already a valid Memanto type. We
put the mapped Memanto type in slot 0 for exactly that reason.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from graphiti_okf.mapping import MappedMemory

ADAPTER_NOTE = (
    "Generated by examples/migrations/graphiti-to-okf. Source system is Graphiti "
    "(Zep), NOT Mem0. This file uses the Mem0 export shape only so the shipped "
    "'memanto migrate mem0 --file' path and its savings report can consume it; "
    "the CLI has no native graphiti provider. Use the OKF bundle for a "
    "full-fidelity import that preserves source='graphiti' and per-record "
    "confidence."
)


def _entities_from_export(export: dict[str, Any]) -> list[dict[str, Any]]:
    """Project Graphiti entity nodes onto the entity shape the report counts."""
    entities: list[dict[str, Any]] = []
    for node in export.get("entity_nodes") or []:
        labels = [x for x in (node.get("labels") or []) if x and x != "Entity"]
        entities.append(
            {
                "id": node.get("uuid"),
                "name": node.get("name"),
                "type": (labels[0] if labels else "entity").lower(),
            }
        )
    return entities


def build_provider_export(
    records: list[MappedMemory],
    raw_export: dict[str, Any],
) -> dict[str, Any]:
    """Build the provider-JSON document."""
    entities = _entities_from_export(raw_export)
    group_ids = {
        str(item.get("group_id"))
        for key in ("entity_edges", "entity_nodes", "episodes", "communities")
        for item in (raw_export.get(key) or [])
        if item.get("group_id")
    }

    memories: list[dict[str, Any]] = []
    for record in records:
        metadata: dict[str, Any] = {
            "graphiti_kind": record.graphiti_kind,
            **{k: v for k, v in record.temporal.items() if v not in (None, "")},
            **{k: v for k, v in record.extra.items() if v not in (None, "")},
            # Preserved here because map_mem0 discards per-record confidence.
            "adapter_confidence": record.confidence,
        }
        memories.append(
            {
                "id": record.source_ref,
                "memory": record.content,
                # Slot 0 drives type resolution in map_mem0.
                "categories": [record.type, *record.tags],
                "created_at": record.created_at.isoformat() if record.created_at else None,
                "metadata": metadata,
                "immutable": False,
            }
        )

    return {
        "_adapter": {
            "note": ADAPTER_NOTE,
            "source_system": "graphiti",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "exported_at": raw_export.get("exported_at"),
        "summary": {
            "entity_count": len(entities),
            "scope_count": len(group_ids) or 1,
            "memory_count": len(memories),
        },
        "entities": entities,
        "memories": memories,
    }


def write_provider_export(
    records: list[MappedMemory],
    raw_export: dict[str, Any],
    output_path: Path,
) -> dict[str, Any]:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    document = build_provider_export(records, raw_export)
    output_path.write_text(
        json.dumps(document, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return document
