#!/usr/bin/env python3
"""Exercise a Codex OKF bundle through Memanto's official import/export code."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import defaultdict
from pathlib import Path
from typing import Any

from memanto.app.services.okf_export_service import OkfExportService
from memanto.cli.migrate.mappers import map_okf
from memanto.cli.migrate.okf_loader import load_okf_bundle

OWNER_MARKER = ".codex-okf-roundtrip"


def _resource(entry: dict[str, Any]) -> str:
    return str(entry.get("resource") or "")


def _type(entry: dict[str, Any]) -> str:
    extension = entry.get("x_memanto") or {}
    return str(extension.get("type") or entry.get("type") or "")


def _prepare_output(path: Path, *, replace: bool) -> None:
    if not path.exists():
        return
    if not replace:
        raise FileExistsError(f"round-trip output already exists: {path}")
    marker = path / OWNER_MARKER
    if not marker.is_file():
        raise ValueError(
            f"refusing to replace unowned directory without {OWNER_MARKER}: {path}"
        )
    shutil.rmtree(path)


def _normalize_generated_markdown(root: Path, timestamp: str) -> None:
    """Make generated presentation-only Markdown deterministic and diff-clean."""
    for path in root.rglob("*.md"):
        rendered = path.read_text(encoding="utf-8")
        if path.name == "index.md" and timestamp:
            rendered = re.sub(
                r"(?m)^timestamp:.*$", f"timestamp: '{timestamp}'", rendered
            )
        normalized = "\n".join(line.rstrip() for line in rendered.splitlines())
        path.write_text(normalized.rstrip() + "\n", encoding="utf-8")


def validate_portability(
    bundle: Path,
    output: Path,
    *,
    replace: bool = False,
) -> dict[str, Any]:
    """Map with Memanto, export again, and compare stable fidelity fields."""
    bundle = bundle.resolve()
    output = output.resolve()
    source_export = load_okf_bundle(bundle)
    source_entries = source_export.get("memories") or []
    mapped = map_okf(source_export)
    if len(mapped) != len(source_entries):
        raise ValueError(
            f"Memanto mapped {len(mapped)} of {len(source_entries)} source memories"
        )

    source_timestamps = sorted(
        str(entry.get("timestamp"))
        for entry in source_entries
        if entry.get("timestamp")
    )

    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for memory in mapped:
        memory_type = str(memory.get("type") or "")
        if not memory_type:
            raise ValueError(f"mapped memory has no type: {memory.get('title')}")
        grouped[memory_type].append(memory)

    _prepare_output(output, replace=replace)
    output.parent.mkdir(parents=True, exist_ok=True)
    service = OkfExportService(exports_dir=output.parent / ".memanto-exports")
    result = service.write_okf_bundle(
        "codex-portability-check",
        dict(grouped),
        output_dir=output,
        split="type",
    )
    _normalize_generated_markdown(
        output, source_timestamps[0] if source_timestamps else ""
    )
    (output / OWNER_MARKER).write_text(
        "Generated by validate_portability.py; safe to replace.\n", encoding="utf-8"
    )

    reexport_entries = load_okf_bundle(output).get("memories") or []
    source_by_resource = {_resource(entry): entry for entry in source_entries}
    reexport_by_resource = {_resource(entry): entry for entry in reexport_entries}
    if "" in source_by_resource or len(source_by_resource) != len(source_entries):
        raise ValueError("source bundle resources must be present and unique")

    cases: list[dict[str, Any]] = []
    for resource, source in sorted(source_by_resource.items()):
        exported = reexport_by_resource.get(resource)
        source_body = str(source.get("body") or "").strip()
        exported_body = str((exported or {}).get("body") or "").strip()
        case = {
            "resource": resource,
            "found": exported is not None,
            "type_preserved": exported is not None and _type(exported) == _type(source),
            "title_preserved": exported is not None
            and str(exported.get("title") or "") == str(source.get("title") or ""),
            "content_preserved": bool(source_body)
            and exported is not None
            and source_body in exported_body,
        }
        case["passed"] = all(
            case[field]
            for field in (
                "found",
                "type_preserved",
                "title_preserved",
                "content_preserved",
            )
        )
        cases.append(case)

    passed = sum(bool(case["passed"]) for case in cases)
    report = {
        "schema": "codex-okf-memanto-portability/v1",
        "pipeline": [
            "OKF source bundle",
            "memanto.cli.migrate.okf_loader.load_okf_bundle",
            "memanto.cli.migrate.mappers.map_okf",
            "memanto.app.services.okf_export_service.OkfExportService",
            "deterministic presentation normalization",
            "re-exported OKF bundle",
        ],
        "source_memories": len(source_entries),
        "mapped_memories": len(mapped),
        "reexported_memories": len(reexport_entries),
        "resources_preserved": sum(bool(case["found"]) for case in cases),
        "types_preserved": sum(bool(case["type_preserved"]) for case in cases),
        "titles_preserved": sum(bool(case["title_preserved"]) for case in cases),
        "content_preserved": sum(bool(case["content_preserved"]) for case in cases),
        "passed": passed,
        "parity_percent": round(100 * passed / len(cases), 1) if cases else 0.0,
        "export_result": {
            "total_memories": result["total_memories"],
            "per_type_counts": result["per_type_counts"],
        },
        "cases": cases,
    }
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("bundle", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--replace", action="store_true")
    args = parser.parse_args()

    report = validate_portability(args.bundle, args.output, replace=args.replace)
    rendered = json.dumps(report, ensure_ascii=False, indent=2) + "\n"
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(rendered, encoding="utf-8")
    print(rendered, end="")
    return 0 if report["parity_percent"] == 100.0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
