"""Generate a genuine Aider/Ollama chat history for the migration demo."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

PROMPTS = (
    "Create assistant_profile.md. Record these durable preferences: concise status labels, no emoji, and ISO 8601 dates.",
    "Update assistant_profile.md with a deployment decision: store timestamps in UTC and display them in America/New_York.",
    "Correction: quiet hours are 22:00-07:00 America/New_York, not 21:00-06:00. Preserve the earlier decision and make the correction explicit.",
    "Summarize every durable preference, decision, and correction currently in assistant_profile.md without changing the file.",
)


def sanitize_history(text: str, repository: Path) -> str:
    """Remove machine-specific paths while leaving Aider's records intact."""

    text = text.replace(str(repository), "<MEMANTO_REPOSITORY>")
    executable = re.compile(
        r"[A-Za-z]:\\Users\\[^\\\r\n]+\\(?:scoop\\persist\\uv|\.cache\\uv)"
        r"\\[^\r\n]*?\\Scripts\\aider(?:\.exe)?"
    )
    return executable.sub("aider", text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="ollama_chat/qwen2.5-coder:3b")
    parser.add_argument(
        "--output", type=Path, default=Path("data/aider.chat.history.md")
    )
    parser.add_argument(
        "--sanitize-only",
        action="store_true",
        help="sanitize an already-generated history without running Aider",
    )
    args = parser.parse_args()
    if shutil.which("ollama") is None:
        raise SystemExit("ollama is required; install it and pull qwen2.5-coder:3b")

    root = Path(__file__).resolve().parent
    workspace = root / "demo_workspace"
    workspace.mkdir(exist_ok=True)
    output = args.output if args.output.is_absolute() else root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    repository = root.parents[2]
    if args.sanitize_only:
        output.write_text(
            sanitize_history(output.read_text(encoding="utf-8"), repository),
            encoding="utf-8",
        )
        print(f"Sanitized machine-specific paths: {output}")
        return 0
    output.unlink(missing_ok=True)

    for prompt in PROMPTS:
        command = [
            "uvx",
            "--python",
            "3.12",
            "--from",
            "aider-chat",
            "aider",
            "--model",
            args.model,
            "--no-git",
            "--yes",
            "--no-stream",
            "--chat-history-file",
            str(output),
            "--message",
            prompt,
        ]
        subprocess.run(command, cwd=workspace, check=True)
    output.write_text(
        sanitize_history(output.read_text(encoding="utf-8"), repository),
        encoding="utf-8",
    )
    print(f"Generated by four real Aider runs: {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
