"""Generate a genuine Aider/Ollama chat history for the migration demo."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from path_scrub import scrub_home_paths

PROMPTS = (
    "Create assistant_profile.md. Record these durable preferences: concise status labels, no emoji, and ISO 8601 dates.",
    "Update assistant_profile.md with a deployment decision: store timestamps in UTC and display them in America/New_York.",
    "Correction: quiet hours are 22:00-07:00 America/New_York, not 21:00-06:00. Preserve the earlier decision and make the correction explicit.",
    "Summarize every durable preference, decision, and correction currently in assistant_profile.md without changing the file.",
)


def sanitize_history(text: str, repository: Path) -> str:
    """Remove machine-specific paths while leaving Aider's records intact."""

    text = text.replace(str(repository), "<MEMANTO_REPOSITORY>")
    executable = re.compile(
        r"[A-Za-z]:\\Users\\[^\\\r\n]+\\(?:scoop\\persist\\uv|\.cache\\uv)"
        r"\\[^\r\n]*?\\Scripts\\aider(?:\.exe)?"
    )
    return scrub_home_paths(executable.sub("aider", text))


def atomic_sanitize(source: Path, destination: Path, repository: Path) -> None:
    """Sanitize a history into a sibling temporary file, then replace atomically."""

    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=destination.parent,
            prefix=f".{destination.name}.sanitized-",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_path = Path(temporary.name)
            temporary.write(
                sanitize_history(source.read_text(encoding="utf-8"), repository)
            )
        temporary_path.replace(destination)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def main() -> int:
    """Generate or sanitize the checked-in Aider source history."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="ollama_chat/qwen2.5-coder:3b")
    parser.add_argument(
        "--output", type=Path, default=Path("data/aider.chat.history.md")
    )
    parser.add_argument(
        "--sanitize-only",
        action="store_true",
        help="sanitize an already-generated history without running Aider",
    )
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    workspace = root / "demo_workspace"
    workspace.mkdir(exist_ok=True)
    output = args.output if args.output.is_absolute() else root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    repository = root.parents[2]
    if args.sanitize_only:
        atomic_sanitize(output, output, repository)
        print(f"Sanitized machine-specific paths: {output}")
        return 0
    if shutil.which("ollama") is None:
        raise SystemExit("ollama is required; install it and pull qwen2.5-coder:3b")

    handle, temporary_name = tempfile.mkstemp(
        dir=output.parent,
        prefix=f".{output.name}.raw-",
        suffix=".tmp",
    )
    temporary_output = Path(temporary_name)
    # Aider opens the path itself; close the descriptor before invoking it.
    os.close(handle)

    try:
        for prompt in PROMPTS:
            command = [
                "uvx",
                "--python",
                "3.12",
                "--from",
                "aider-chat==0.86.2",
                "aider",
                "--model",
                args.model,
                "--no-git",
                "--yes",
                "--no-stream",
                "--chat-history-file",
                str(temporary_output),
                "--message",
                prompt,
            ]
            subprocess.run(command, cwd=workspace, check=True)
        atomic_sanitize(temporary_output, output, repository)
    finally:
        temporary_output.unlink(missing_ok=True)
    print(f"Generated by four real Aider runs: {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
