// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentPattern.
const (
	Project AgentPattern = "project"
	Support AgentPattern = "support"
	Tool    AgentPattern = "tool"
)

// Valid indicates whether the value is a known member of the AgentPattern enum.
func (e AgentPattern) Valid() bool {
	switch e {
	case Project:
		return true
	case Support:
		return true
	case Tool:
		return true
	default:
		return false
	}
}

// Defines values for BatchRememberItemType.
const (
	BatchRememberItemTypeArtifact     BatchRememberItemType = "artifact"
	BatchRememberItemTypeCommitment   BatchRememberItemType = "commitment"
	BatchRememberItemTypeContext      BatchRememberItemType = "context"
	BatchRememberItemTypeDecision     BatchRememberItemType = "decision"
	BatchRememberItemTypeError        BatchRememberItemType = "error"
	BatchRememberItemTypeEvent        BatchRememberItemType = "event"
	BatchRememberItemTypeFact         BatchRememberItemType = "fact"
	BatchRememberItemTypeGoal         BatchRememberItemType = "goal"
	BatchRememberItemTypeInstruction  BatchRememberItemType = "instruction"
	BatchRememberItemTypeLearning     BatchRememberItemType = "learning"
	BatchRememberItemTypeObservation  BatchRememberItemType = "observation"
	BatchRememberItemTypePreference   BatchRememberItemType = "preference"
	BatchRememberItemTypeRelationship BatchRememberItemType = "relationship"
)

// Valid indicates whether the value is a known member of the BatchRememberItemType enum.
func (e BatchRememberItemType) Valid() bool {
	switch e {
	case BatchRememberItemTypeArtifact:
		return true
	case BatchRememberItemTypeCommitment:
		return true
	case BatchRememberItemTypeContext:
		return true
	case BatchRememberItemTypeDecision:
		return true
	case BatchRememberItemTypeError:
		return true
	case BatchRememberItemTypeEvent:
		return true
	case BatchRememberItemTypeFact:
		return true
	case BatchRememberItemTypeGoal:
		return true
	case BatchRememberItemTypeInstruction:
		return true
	case BatchRememberItemTypeLearning:
		return true
	case BatchRememberItemTypeObservation:
		return true
	case BatchRememberItemTypePreference:
		return true
	case BatchRememberItemTypeRelationship:
		return true
	default:
		return false
	}
}

// Defines values for ConflictResolveRequestAction.
const (
	ExpireBoth ConflictResolveRequestAction = "expire_both"
	ExpireNew  ConflictResolveRequestAction = "expire_new"
	ExpireOld  ConflictResolveRequestAction = "expire_old"
	KeepBoth   ConflictResolveRequestAction = "keep_both"
	KeepNew    ConflictResolveRequestAction = "keep_new"
	KeepOld    ConflictResolveRequestAction = "keep_old"
	Manual     ConflictResolveRequestAction = "manual"
	RemoveBoth ConflictResolveRequestAction = "remove_both"
)

// Valid indicates whether the value is a known member of the ConflictResolveRequestAction enum.
func (e ConflictResolveRequestAction) Valid() bool {
	switch e {
	case ExpireBoth:
		return true
	case ExpireNew:
		return true
	case ExpireOld:
		return true
	case KeepBoth:
		return true
	case KeepNew:
		return true
	case KeepOld:
		return true
	case Manual:
		return true
	case RemoveBoth:
		return true
	default:
		return false
	}
}

// Defines values for MemoryEditRequestType.
const (
	MemoryEditRequestTypeArtifact     MemoryEditRequestType = "artifact"
	MemoryEditRequestTypeCommitment   MemoryEditRequestType = "commitment"
	MemoryEditRequestTypeContext      MemoryEditRequestType = "context"
	MemoryEditRequestTypeDecision     MemoryEditRequestType = "decision"
	MemoryEditRequestTypeError        MemoryEditRequestType = "error"
	MemoryEditRequestTypeEvent        MemoryEditRequestType = "event"
	MemoryEditRequestTypeFact         MemoryEditRequestType = "fact"
	MemoryEditRequestTypeGoal         MemoryEditRequestType = "goal"
	MemoryEditRequestTypeInstruction  MemoryEditRequestType = "instruction"
	MemoryEditRequestTypeLearning     MemoryEditRequestType = "learning"
	MemoryEditRequestTypeObservation  MemoryEditRequestType = "observation"
	MemoryEditRequestTypePreference   MemoryEditRequestType = "preference"
	MemoryEditRequestTypeRelationship MemoryEditRequestType = "relationship"
)

// Valid indicates whether the value is a known member of the MemoryEditRequestType enum.
func (e MemoryEditRequestType) Valid() bool {
	switch e {
	case MemoryEditRequestTypeArtifact:
		return true
	case MemoryEditRequestTypeCommitment:
		return true
	case MemoryEditRequestTypeContext:
		return true
	case MemoryEditRequestTypeDecision:
		return true
	case MemoryEditRequestTypeError:
		return true
	case MemoryEditRequestTypeEvent:
		return true
	case MemoryEditRequestTypeFact:
		return true
	case MemoryEditRequestTypeGoal:
		return true
	case MemoryEditRequestTypeInstruction:
		return true
	case MemoryEditRequestTypeLearning:
		return true
	case MemoryEditRequestTypeObservation:
		return true
	case MemoryEditRequestTypePreference:
		return true
	case MemoryEditRequestTypeRelationship:
		return true
	default:
		return false
	}
}

// Defines values for PolicyMatchProvenance.
const (
	Corrected         PolicyMatchProvenance = "corrected"
	ExplicitStatement PolicyMatchProvenance = "explicit_statement"
	Imported          PolicyMatchProvenance = "imported"
	Inferred          PolicyMatchProvenance = "inferred"
	Observed          PolicyMatchProvenance = "observed"
	Validated         PolicyMatchProvenance = "validated"
)

// Valid indicates whether the value is a known member of the PolicyMatchProvenance enum.
func (e PolicyMatchProvenance) Valid() bool {
	switch e {
	case Corrected:
		return true
	case ExplicitStatement:
		return true
	case Imported:
		return true
	case Inferred:
		return true
	case Observed:
		return true
	case Validated:
		return true
	default:
		return false
	}
}

// Defines values for PolicyMatchType.
const (
	PolicyMatchTypeArtifact     PolicyMatchType = "artifact"
	PolicyMatchTypeCommitment   PolicyMatchType = "commitment"
	PolicyMatchTypeContext      PolicyMatchType = "context"
	PolicyMatchTypeDecision     PolicyMatchType = "decision"
	PolicyMatchTypeError        PolicyMatchType = "error"
	PolicyMatchTypeEvent        PolicyMatchType = "event"
	PolicyMatchTypeFact         PolicyMatchType = "fact"
	PolicyMatchTypeGoal         PolicyMatchType = "goal"
	PolicyMatchTypeInstruction  PolicyMatchType = "instruction"
	PolicyMatchTypeLearning     PolicyMatchType = "learning"
	PolicyMatchTypeObservation  PolicyMatchType = "observation"
	PolicyMatchTypePreference   PolicyMatchType = "preference"
	PolicyMatchTypeRelationship PolicyMatchType = "relationship"
)

// Valid indicates whether the value is a known member of the PolicyMatchType enum.
func (e PolicyMatchType) Valid() bool {
	switch e {
	case PolicyMatchTypeArtifact:
		return true
	case PolicyMatchTypeCommitment:
		return true
	case PolicyMatchTypeContext:
		return true
	case PolicyMatchTypeDecision:
		return true
	case PolicyMatchTypeError:
		return true
	case PolicyMatchTypeEvent:
		return true
	case PolicyMatchTypeFact:
		return true
	case PolicyMatchTypeGoal:
		return true
	case PolicyMatchTypeInstruction:
		return true
	case PolicyMatchTypeLearning:
		return true
	case PolicyMatchTypeObservation:
		return true
	case PolicyMatchTypePreference:
		return true
	case PolicyMatchTypeRelationship:
		return true
	default:
		return false
	}
}

// Defines values for RecallChangedSinceRequestStatus.
const (
	RecallChangedSinceRequestStatusActive  RecallChangedSinceRequestStatus = "active"
	RecallChangedSinceRequestStatusAll     RecallChangedSinceRequestStatus = "all"
	RecallChangedSinceRequestStatusExpired RecallChangedSinceRequestStatus = "expired"
)

// Valid indicates whether the value is a known member of the RecallChangedSinceRequestStatus enum.
func (e RecallChangedSinceRequestStatus) Valid() bool {
	switch e {
	case RecallChangedSinceRequestStatusActive:
		return true
	case RecallChangedSinceRequestStatusAll:
		return true
	case RecallChangedSinceRequestStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for RecallRecentRequestStatus.
const (
	RecallRecentRequestStatusActive  RecallRecentRequestStatus = "active"
	RecallRecentRequestStatusAll     RecallRecentRequestStatus = "all"
	RecallRecentRequestStatusExpired RecallRecentRequestStatus = "expired"
)

// Valid indicates whether the value is a known member of the RecallRecentRequestStatus enum.
func (e RecallRecentRequestStatus) Valid() bool {
	switch e {
	case RecallRecentRequestStatusActive:
		return true
	case RecallRecentRequestStatusAll:
		return true
	case RecallRecentRequestStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for RecallRequestStatus.
const (
	RecallRequestStatusActive  RecallRequestStatus = "active"
	RecallRequestStatusAll     RecallRequestStatus = "all"
	RecallRequestStatusExpired RecallRequestStatus = "expired"
)

// Valid indicates whether the value is a known member of the RecallRequestStatus enum.
func (e RecallRequestStatus) Valid() bool {
	switch e {
	case RecallRequestStatusActive:
		return true
	case RecallRequestStatusAll:
		return true
	case RecallRequestStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for RememberRequestType.
const (
	RememberRequestTypeArtifact     RememberRequestType = "artifact"
	RememberRequestTypeCommitment   RememberRequestType = "commitment"
	RememberRequestTypeContext      RememberRequestType = "context"
	RememberRequestTypeDecision     RememberRequestType = "decision"
	RememberRequestTypeError        RememberRequestType = "error"
	RememberRequestTypeEvent        RememberRequestType = "event"
	RememberRequestTypeFact         RememberRequestType = "fact"
	RememberRequestTypeGoal         RememberRequestType = "goal"
	RememberRequestTypeInstruction  RememberRequestType = "instruction"
	RememberRequestTypeLearning     RememberRequestType = "learning"
	RememberRequestTypeObservation  RememberRequestType = "observation"
	RememberRequestTypePreference   RememberRequestType = "preference"
	RememberRequestTypeRelationship RememberRequestType = "relationship"
)

// Valid indicates whether the value is a known member of the RememberRequestType enum.
func (e RememberRequestType) Valid() bool {
	switch e {
	case RememberRequestTypeArtifact:
		return true
	case RememberRequestTypeCommitment:
		return true
	case RememberRequestTypeContext:
		return true
	case RememberRequestTypeDecision:
		return true
	case RememberRequestTypeError:
		return true
	case RememberRequestTypeEvent:
		return true
	case RememberRequestTypeFact:
		return true
	case RememberRequestTypeGoal:
		return true
	case RememberRequestTypeInstruction:
		return true
	case RememberRequestTypeLearning:
		return true
	case RememberRequestTypeObservation:
		return true
	case RememberRequestTypePreference:
		return true
	case RememberRequestTypeRelationship:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusActive     SessionStatus = "active"
	SessionStatusExpired    SessionStatus = "expired"
	SessionStatusTerminated SessionStatus = "terminated"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusActive:
		return true
	case SessionStatusExpired:
		return true
	case SessionStatusTerminated:
		return true
	default:
		return false
	}
}

// AgentCreate Request to create a new agent
type AgentCreate struct {
	// AgentId Unique agent identifier (alphanumeric, hyphens, underscores)
	AgentId string `json:"agent_id"`

	// Description Human-readable description of the agent
	Description *string `json:"description,omitempty"`

	// Pattern Agent pattern for memory organization
	Pattern *AgentPattern `json:"pattern,omitempty"`
}

// AgentInfo Agent information
type AgentInfo struct {
	AgentId     string     `json:"agent_id"`
	CreatedAt   time.Time  `json:"created_at"`
	Description *string    `json:"description,omitempty"`
	LastSession *time.Time `json:"last_session,omitempty"`
	MemoryCount *int       `json:"memory_count,omitempty"`
	Namespace   string     `json:"namespace"`

	// Pattern Agent pattern types for memory organization
	Pattern      AgentPattern `json:"pattern"`
	SessionCount *int         `json:"session_count,omitempty"`
	Status       *string      `json:"status,omitempty"`
}

// AgentList List of agents
type AgentList struct {
	Agents   []AgentInfo `json:"agents"`
	Count    int         `json:"count"`
	Warnings *[]string   `json:"warnings,omitempty"`
}

// AgentPattern Agent pattern types for memory organization
type AgentPattern string

// AnswerRequest Request body for answer endpoint
type AnswerRequest struct {
	// AiModel AI model to use for generating the answer
	AiModel *string `json:"ai_model,omitempty"`

	// KioskMode Kiosk mode setting
	KioskMode *bool `json:"kiosk_mode,omitempty"`

	// Limit Number of context memories to use
	Limit *int `json:"limit,omitempty"`

	// Question Question to ask
	Question string `json:"question"`

	// Temperature Temperature for the LLM response
	Temperature *float32 `json:"temperature,omitempty"`

	// Threshold Confidence threshold (used only in kiosk mode)
	Threshold *float32 `json:"threshold,omitempty"`
}

// AnswerResponse defines model for AnswerResponse.
type AnswerResponse struct {
	AgentId   string         `json:"agent_id"`
	Answer    string         `json:"answer"`
	Namespace string         `json:"namespace"`
	Question  string         `json:"question"`
	SessionId string         `json:"session_id"`
	Sources   *[]interface{} `json:"sources,omitempty"`
}

// BatchRememberItem Single memory item in a batch-remember request
type BatchRememberItem struct {
	// Confidence Confidence score (0-1)
	Confidence *float32 `json:"confidence,omitempty"`

	// Content Memory content
	Content string `json:"content"`

	// Provenance How memory was obtained (explicit_statement, inferred, observed, etc.)
	Provenance *string `json:"provenance,omitempty"`

	// Source Who wrote this memory — 'user', 'agent', or a specific writer such as 'cursor', 'codex', or 'claude_code'.
	Source *string `json:"source,omitempty"`

	// Tags Tags for this memory
	Tags *[]string `json:"tags,omitempty"`

	// Title Memory title (defaults to truncated content)
	Title *string `json:"title,omitempty"`

	// Type Memory type. Omit to auto-parse.
	Type *BatchRememberItemType `json:"type,omitempty"`
}

// BatchRememberItemType defines model for BatchRememberItem.Type.
type BatchRememberItemType string

// BatchRememberRequest Request body for batch-remember endpoint
type BatchRememberRequest struct {
	// Memories List of memories to store (max 100)
	Memories []BatchRememberItem `json:"memories"`
}

// BatchRememberResponse defines model for BatchRememberResponse.
type BatchRememberResponse struct {
	AgentId        string                    `json:"agent_id"`
	Failed         int                       `json:"failed"`
	Namespace      string                    `json:"namespace"`
	Results        []BatchRememberResultItem `json:"results"`
	SessionId      string                    `json:"session_id"`
	Successful     int                       `json:"successful"`
	TotalSubmitted int                       `json:"total_submitted"`
}

// BatchRememberResultItem defines model for BatchRememberResultItem.
type BatchRememberResultItem struct {
	Action *string `json:"action,omitempty"`
	Error  *string `json:"error,omitempty"`
	Id     string  `json:"id"`
	Reason *string `json:"reason,omitempty"`
	Status string  `json:"status"`
	Type   *string `json:"type,omitempty"`
}

// BodyUploadFileApiV2AgentsAgentIdUploadFilePost defines model for Body_upload_file_api_v2_agents__agent_id__upload_file_post.
type BodyUploadFileApiV2AgentsAgentIdUploadFilePost struct {
	// File File to upload (.pdf, .docx, .xlsx, .json, .txt, .csv, .md)
	File openapi_types.File `json:"file"`
}

// ConflictDetectRequest Request body for on-demand conflict report generation.
type ConflictDetectRequest struct {
	// Date Date string YYYY-MM-DD. Defaults to today.
	Date *string `json:"date,omitempty"`
}

// ConflictResolveRequest Request body for resolving a conflict
type ConflictResolveRequest struct {
	// Action Resolution action. The keep_*/remove_both/manual actions delete the losing memory permanently; the expire_* actions retire it reversibly instead, keeping its content and audit trail.
	Action ConflictResolveRequestAction `json:"action"`

	// ConflictIndex Conflict index to resolve
	ConflictIndex int `json:"conflict_index"`

	// Date Conflict report date (YYYY-MM-DD). Defaults to today.
	Date *string `json:"date,omitempty"`

	// ManualContent Required when action is 'manual'
	ManualContent *string `json:"manual_content,omitempty"`

	// ManualType Optional memory type for manual action
	ManualType *string `json:"manual_type,omitempty"`
}

// ConflictResolveRequestAction Resolution action. The keep_*/remove_both/manual actions delete the losing memory permanently; the expire_* actions retire it reversibly instead, keeping its content and audit trail.
type ConflictResolveRequestAction string

// ConversationMessage Chat-style message used for conversation memory extraction.
type ConversationMessage struct {
	Content string `json:"content"`
	Role    string `json:"role"`
}

// DailySummaryRequest Request body for on-demand daily summary generation.
type DailySummaryRequest struct {
	// Date Date string YYYY-MM-DD. Defaults to today.
	Date *string `json:"date,omitempty"`

	// OutputPath Accepted for backwards compatibility but ignored; summaries use the server-controlled output location.
	OutputPath *string `json:"output_path,omitempty"`
}

// ExtractMemoriesRequest Request body for extracting typed memories from conversation turns.
type ExtractMemoriesRequest struct {
	// AiModel Optional model override for extraction
	AiModel *string `json:"ai_model,omitempty"`

	// DryRun When true, return candidates without storing them
	DryRun *bool `json:"dry_run,omitempty"`

	// MaxMemories Maximum candidate memories to extract
	MaxMemories *int `json:"max_memories,omitempty"`

	// Messages Conversation turns to extract durable memories from
	Messages []ConversationMessage `json:"messages"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	MoorchehConnected bool   `json:"moorcheh_connected"`
	Service           string `json:"service"`
	Status            string `json:"status"`
	Version           string `json:"version"`
}

// MemoryEditRequest Request body for partial memory record updates.
type MemoryEditRequest struct {
	Confidence *float32               `json:"confidence,omitempty"`
	Content    *string                `json:"content,omitempty"`
	Source     *string                `json:"source,omitempty"`
	Tags       *[]string              `json:"tags,omitempty"`
	Title      *string                `json:"title,omitempty"`
	Type       *MemoryEditRequestType `json:"type,omitempty"`
}

// MemoryEditRequestType defines model for MemoryEditRequest.Type.
type MemoryEditRequestType string

// MemoryExpireRequest Request body for expiring a single memory.
type MemoryExpireRequest struct {
	// Reason Why this memory expired, stamped as `expired_by`. Defaults to 'manual'. Bounded to letters, digits, '.', '_' and '-'.
	Reason *string `json:"reason,omitempty"`
}

// MemoryItem Single memory record as returned by recall/answer endpoints.
type MemoryItem struct {
	ActorId    *string   `json:"actor_id,omitempty"`
	AgentId    *string   `json:"agent_id,omitempty"`
	ChangeType *string   `json:"change_type,omitempty"`
	Confidence *float32  `json:"confidence,omitempty"`
	Content    *string   `json:"content,omitempty"`
	CreatedAt  *string   `json:"created_at,omitempty"`
	ExpiredAt  *string   `json:"expired_at,omitempty"`
	ExpiredBy  *string   `json:"expired_by,omitempty"`
	Id         *string   `json:"id,omitempty"`
	Provenance *string   `json:"provenance,omitempty"`
	Score      *float32  `json:"score,omitempty"`
	Source     *string   `json:"source,omitempty"`
	SourceRef  *string   `json:"source_ref,omitempty"`
	Status     *string   `json:"status,omitempty"`
	Tags       *[]string `json:"tags,omitempty"`
	Text       *string   `json:"text,omitempty"`
	Title      *string   `json:"title,omitempty"`
	Type       *string   `json:"type,omitempty"`
	UpdatedAt  *string   `json:"updated_at,omitempty"`
}

// MemoryPolicy The full expiry policy for one agent.
type MemoryPolicy struct {
	PurgeExpiredAfter *string            `json:"purge_expired_after,omitempty"`
	Retention         *map[string]string `json:"retention,omitempty"`
	Rules             *[]PolicyRule      `json:"rules,omitempty"`
	Version           *int               `json:"version,omitempty"`
}

// PolicyApplyRequest Request body for a policy sweep or purge.
type PolicyApplyRequest struct {
	// DryRun Report what would change without writing anything
	DryRun *bool `json:"dry_run,omitempty"`
}

// PolicyMatch Conditions a memory must satisfy for a rule to fire.
//
// Every field that is set must match (AND). An empty match block matches
// every memory, which is how a catch-all rule is written.
type PolicyMatch struct {
	ConfidenceBelow *float32                 `json:"confidence_below,omitempty"`
	Provenance      *[]PolicyMatchProvenance `json:"provenance,omitempty"`
	Source          *[]string                `json:"source,omitempty"`
	Tags            *[]string                `json:"tags,omitempty"`
	Type            *[]PolicyMatchType       `json:"type,omitempty"`
}

// PolicyMatchProvenance defines model for PolicyMatch.Provenance.
type PolicyMatchProvenance string

// PolicyMatchType defines model for PolicyMatch.Type.
type PolicyMatchType string

// PolicyPresetRequest Request body for adopting a predefined policy bundle.
type PolicyPresetRequest struct {
	// Name Preset name, e.g. 'balanced'
	Name string `json:"name"`
}

// PolicyRule A named expiry rule. “name“ is stamped onto the memory as
// “expired_by“, so it is bounded to the Moorcheh filter-token charset.
type PolicyRule struct {
	ExpireAfter *string `json:"expire_after,omitempty"`

	// Match Conditions a memory must satisfy for a rule to fire.
	//
	// Every field that is set must match (AND). An empty match block matches
	// every memory, which is how a catch-all rule is written.
	Match *PolicyMatch `json:"match,omitempty"`
	Name  string       `json:"name"`
}

// RecallAsOfRequest Request body for point-in-time memory recall.
type RecallAsOfRequest struct {
	// AsOf Point-in-time — YYYY-MM-DD (defaults to end of day) or full ISO datetime e.g. 2025-11-01T14:30:00Z
	AsOf time.Time `json:"as_of"`

	// Limit Max results
	Limit *int `json:"limit,omitempty"`

	// Tags Tag filters
	Tags *[]string `json:"tags,omitempty"`

	// Type Memory type filters
	Type *[]string `json:"type,omitempty"`
}

// RecallChangedSinceRequest Request body for querying memories changed since a timestamp.
type RecallChangedSinceRequest struct {
	// Limit Max results
	Limit *int `json:"limit,omitempty"`

	// Since Start of change window — YYYY-MM-DD (defaults to start of day) or full ISO datetime e.g. 2025-11-01T00:00:00Z
	Since time.Time `json:"since"`

	// Status Lifecycle filter: 'all' (default) returns active and expired memories together so callers can label them, 'active' or 'expired' narrows to one.
	Status *RecallChangedSinceRequestStatus `json:"status,omitempty"`

	// Tags Tag filters
	Tags *[]string `json:"tags,omitempty"`

	// Type Memory type filters
	Type *[]string `json:"type,omitempty"`
}

// RecallChangedSinceRequestStatus Lifecycle filter: 'all' (default) returns active and expired memories together so callers can label them, 'active' or 'expired' narrows to one.
type RecallChangedSinceRequestStatus string

// RecallRecentRequest Request body for retrieving recent memories.
type RecallRecentRequest struct {
	// CreatedAfter Include only memories created at or after this timestamp. Date-only values (YYYY-MM-DD) use the start of that day.
	CreatedAfter *RecallRecentRequest_CreatedAfter `json:"created_after,omitempty"`

	// CreatedBefore Include only memories created at or before this timestamp. Date-only values (YYYY-MM-DD) use the end of that day.
	CreatedBefore *RecallRecentRequest_CreatedBefore `json:"created_before,omitempty"`

	// Limit Max results
	Limit *int `json:"limit,omitempty"`

	// Status Lifecycle filter: 'all' (default) returns active and expired memories together so callers can label them, 'active' or 'expired' narrows to one.
	Status *RecallRecentRequestStatus `json:"status,omitempty"`

	// Tags Tag filters
	Tags *[]string `json:"tags,omitempty"`

	// Type Memory type filters
	Type *[]string `json:"type,omitempty"`
}

// RecallRecentRequestCreatedAfter0 defines model for RecallRecentRequest.CreatedAfter.0.
type RecallRecentRequestCreatedAfter0 = time.Time

// RecallRecentRequestCreatedAfter1 defines model for RecallRecentRequest.CreatedAfter.1.
type RecallRecentRequestCreatedAfter1 = openapi_types.Date

// RecallRecentRequest_CreatedAfter Include only memories created at or after this timestamp. Date-only values (YYYY-MM-DD) use the start of that day.
type RecallRecentRequest_CreatedAfter struct {
	union json.RawMessage
}

// RecallRecentRequestCreatedBefore0 defines model for RecallRecentRequest.CreatedBefore.0.
type RecallRecentRequestCreatedBefore0 = time.Time

// RecallRecentRequestCreatedBefore1 defines model for RecallRecentRequest.CreatedBefore.1.
type RecallRecentRequestCreatedBefore1 = openapi_types.Date

// RecallRecentRequest_CreatedBefore Include only memories created at or before this timestamp. Date-only values (YYYY-MM-DD) use the end of that day.
type RecallRecentRequest_CreatedBefore struct {
	union json.RawMessage
}

// RecallRecentRequestStatus Lifecycle filter: 'all' (default) returns active and expired memories together so callers can label them, 'active' or 'expired' narrows to one.
type RecallRecentRequestStatus string

// RecallRequest Request body for semantic memory recall.
type RecallRequest struct {
	// CreatedAfter Include only memories created at or after this timestamp. Date-only values (YYYY-MM-DD) use the start of that day.
	CreatedAfter *RecallRequest_CreatedAfter `json:"created_after,omitempty"`

	// CreatedBefore Include only memories created at or before this timestamp. Date-only values (YYYY-MM-DD) use the end of that day.
	CreatedBefore *RecallRequest_CreatedBefore `json:"created_before,omitempty"`

	// Limit Max results
	Limit *int `json:"limit,omitempty"`

	// MinSimilarity Minimum similarity score (0-1)
	MinSimilarity *float32 `json:"min_similarity,omitempty"`

	// Query Search query
	Query string `json:"query"`

	// Status Lifecycle filter: 'all' (default) returns active and expired memories together so callers can label them, 'active' or 'expired' narrows to one.
	Status *RecallRequestStatus `json:"status,omitempty"`

	// Tags Tag filters
	Tags *[]string `json:"tags,omitempty"`

	// Type Memory type filters
	Type *[]string `json:"type,omitempty"`
}

// RecallRequestCreatedAfter0 defines model for RecallRequest.CreatedAfter.0.
type RecallRequestCreatedAfter0 = time.Time

// RecallRequestCreatedAfter1 defines model for RecallRequest.CreatedAfter.1.
type RecallRequestCreatedAfter1 = openapi_types.Date

// RecallRequest_CreatedAfter Include only memories created at or after this timestamp. Date-only values (YYYY-MM-DD) use the start of that day.
type RecallRequest_CreatedAfter struct {
	union json.RawMessage
}

// RecallRequestCreatedBefore0 defines model for RecallRequest.CreatedBefore.0.
type RecallRequestCreatedBefore0 = time.Time

// RecallRequestCreatedBefore1 defines model for RecallRequest.CreatedBefore.1.
type RecallRequestCreatedBefore1 = openapi_types.Date

// RecallRequest_CreatedBefore Include only memories created at or before this timestamp. Date-only values (YYYY-MM-DD) use the end of that day.
type RecallRequest_CreatedBefore struct {
	union json.RawMessage
}

// RecallRequestStatus Lifecycle filter: 'all' (default) returns active and expired memories together so callers can label them, 'active' or 'expired' narrows to one.
type RecallRequestStatus string

// RecallResponse defines model for RecallResponse.
type RecallResponse struct {
	AgentId   string       `json:"agent_id"`
	Count     int          `json:"count"`
	Memories  []MemoryItem `json:"memories"`
	Query     string       `json:"query"`
	SessionId string       `json:"session_id"`
}

// RememberRequest Request body for remember endpoint
type RememberRequest struct {
	// Confidence Confidence score (0-1)
	Confidence *float32 `json:"confidence,omitempty"`

	// Content Memory content
	Content string `json:"content"`

	// Provenance How memory was obtained (explicit_statement, inferred, observed, etc.)
	Provenance *string `json:"provenance,omitempty"`

	// Source Who wrote this memory — 'user', 'agent', or a specific writer such as 'cursor', 'codex', or 'claude_code'.
	Source *string `json:"source,omitempty"`

	// Tags Tags for this memory
	Tags *[]string `json:"tags,omitempty"`

	// Title Memory title (defaults to truncated content)
	Title *string `json:"title,omitempty"`

	// Type Memory type. Omit to auto-parse.
	Type *RememberRequestType `json:"type,omitempty"`
}

// RememberRequestType defines model for RememberRequest.Type.
type RememberRequestType string

// RememberResponse defines model for RememberResponse.
type RememberResponse struct {
	AgentId    string  `json:"agent_id"`
	Confidence float32 `json:"confidence"`
	MemoryId   string  `json:"memory_id"`
	Namespace  string  `json:"namespace"`
	Provenance string  `json:"provenance"`
	SessionId  string  `json:"session_id"`
	Status     string  `json:"status"`
	Type       *string `json:"type,omitempty"`
}

// Session Active session information
type Session struct {
	AgentId      string                  `json:"agent_id"`
	ExpiresAt    time.Time               `json:"expires_at"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	Namespace    string                  `json:"namespace"`
	Pattern      *AgentPattern           `json:"pattern,omitempty"`
	SessionId    string                  `json:"session_id"`
	SessionToken string                  `json:"session_token"`
	StartedAt    time.Time               `json:"started_at"`

	// Status Session status enum
	Status *SessionStatus `json:"status,omitempty"`
}

// SessionInfo Session information response
type SessionInfo struct {
	AgentId   string        `json:"agent_id"`
	ExpiresAt time.Time     `json:"expires_at"`
	Namespace string        `json:"namespace"`
	Pattern   *AgentPattern `json:"pattern,omitempty"`
	SessionId string        `json:"session_id"`
	StartedAt time.Time     `json:"started_at"`

	// Status Session status enum
	Status               SessionStatus `json:"status"`
	TimeRemainingSeconds int           `json:"time_remaining_seconds"`
}

// SessionStatus Session status enum
type SessionStatus string

// SessionSummary Summary of ended session
type SessionSummary struct {
	AgentId         string    `json:"agent_id"`
	DurationHours   float32   `json:"duration_hours"`
	EndedAt         time.Time `json:"ended_at"`
	MemoriesCreated int       `json:"memories_created"`
	SessionId       string    `json:"session_id"`
	StartedAt       time.Time `json:"started_at"`
	SummaryMemoryId *string   `json:"summary_memory_id,omitempty"`
}

// TemporalRecallResponse defines model for TemporalRecallResponse.
type TemporalRecallResponse struct {
	AgentId        string       `json:"agent_id"`
	AsOfDate       *string      `json:"as_of_date,omitempty"`
	Count          int          `json:"count"`
	Memories       []MemoryItem `json:"memories"`
	SessionId      string       `json:"session_id"`
	SinceDate      *string      `json:"since_date,omitempty"`
	TemporalMode   string       `json:"temporal_mode"`
	TotalAvailable *int         `json:"total_available,omitempty"`
}

// UploadFileResponse defines model for UploadFileResponse.
type UploadFileResponse struct {
	AgentId   string  `json:"agent_id"`
	FileName  string  `json:"file_name"`
	FileSize  *int    `json:"file_size,omitempty"`
	Message   *string `json:"message,omitempty"`
	Namespace string  `json:"namespace"`
	SessionId string  `json:"session_id"`
	Status    string  `json:"status"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for ValidationError.Loc.0.
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for ValidationError.Loc.1.
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// ListAgentsApiV2AgentsGetParams defines parameters for ListAgentsApiV2AgentsGet.
type ListAgentsApiV2AgentsGetParams struct {
	// IncludeCounts Whether to fetch live memory counts from Moorcheh (slow for many namespaces)
	IncludeCounts *bool   `form:"include_counts,omitempty" json:"include_counts,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
	XApiKey       *string `json:"X-Api-Key,omitempty"`
}

// CreateAgentApiV2AgentsPostParams defines parameters for CreateAgentApiV2AgentsPost.
type CreateAgentApiV2AgentsPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
	XApiKey       *string `json:"X-Api-Key,omitempty"`
}

// DeleteAgentApiV2AgentsAgentIdDeleteParams defines parameters for DeleteAgentApiV2AgentsAgentIdDelete.
type DeleteAgentApiV2AgentsAgentIdDeleteParams struct {
	// DeleteBackupToo Delete Moorcheh namespace backup
	DeleteBackupToo *bool   `form:"delete-backup-too,omitempty" json:"delete-backup-too,omitempty"`
	Authorization   *string `json:"authorization,omitempty"`
	XApiKey         *string `json:"X-Api-Key,omitempty"`
}

// GetAgentApiV2AgentsAgentIdGetParams defines parameters for GetAgentApiV2AgentsAgentIdGet.
type GetAgentApiV2AgentsAgentIdGetParams struct {
	// IncludeCounts Whether to fetch live memory counts from Moorcheh
	IncludeCounts *bool   `form:"include_counts,omitempty" json:"include_counts,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
	XApiKey       *string `json:"X-Api-Key,omitempty"`
}

// ActivateAgentApiV2AgentsAgentIdActivatePostParams defines parameters for ActivateAgentApiV2AgentsAgentIdActivatePost.
type ActivateAgentApiV2AgentsAgentIdActivatePostParams struct {
	Authorization *string `json:"authorization,omitempty"`
	XApiKey       *string `json:"X-Api-Key,omitempty"`
}

// AnswerApiV2AgentsAgentIdAnswerPostParams defines parameters for AnswerApiV2AgentsAgentIdAnswerPost.
type AnswerApiV2AgentsAgentIdAnswerPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// BatchRememberApiV2AgentsAgentIdBatchRememberPostParams defines parameters for BatchRememberApiV2AgentsAgentIdBatchRememberPost.
type BatchRememberApiV2AgentsAgentIdBatchRememberPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// ListConflictsApiV2AgentsAgentIdConflictsGetParams defines parameters for ListConflictsApiV2AgentsAgentIdConflictsGet.
type ListConflictsApiV2AgentsAgentIdConflictsGetParams struct {
	// Date Conflict report date (YYYY-MM-DD)
	Date                *string `form:"date,omitempty" json:"date,omitempty"`
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// GenerateConflictReportApiV2AgentsAgentIdConflictsGeneratePostParams defines parameters for GenerateConflictReportApiV2AgentsAgentIdConflictsGeneratePost.
type GenerateConflictReportApiV2AgentsAgentIdConflictsGeneratePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// ResolveConflictApiV2AgentsAgentIdConflictsResolvePostParams defines parameters for ResolveConflictApiV2AgentsAgentIdConflictsResolvePost.
type ResolveConflictApiV2AgentsAgentIdConflictsResolvePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// GenerateDailySummaryApiV2AgentsAgentIdDailySummaryPostParams defines parameters for GenerateDailySummaryApiV2AgentsAgentIdDailySummaryPost.
type GenerateDailySummaryApiV2AgentsAgentIdDailySummaryPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// DeactivateAgentApiV2AgentsAgentIdDeactivatePostParams defines parameters for DeactivateAgentApiV2AgentsAgentIdDeactivatePost.
type DeactivateAgentApiV2AgentsAgentIdDeactivatePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// DeleteMemoryApiV2AgentsAgentIdMemoriesMemoryIdDeleteParams defines parameters for DeleteMemoryApiV2AgentsAgentIdMemoriesMemoryIdDelete.
type DeleteMemoryApiV2AgentsAgentIdMemoriesMemoryIdDeleteParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// EditMemoryApiV2AgentsAgentIdMemoriesMemoryIdPatchParams defines parameters for EditMemoryApiV2AgentsAgentIdMemoriesMemoryIdPatch.
type EditMemoryApiV2AgentsAgentIdMemoriesMemoryIdPatchParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// ExpireMemoryApiV2AgentsAgentIdMemoriesMemoryIdExpirePostParams defines parameters for ExpireMemoryApiV2AgentsAgentIdMemoriesMemoryIdExpirePost.
type ExpireMemoryApiV2AgentsAgentIdMemoriesMemoryIdExpirePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// RestoreMemoryApiV2AgentsAgentIdMemoriesMemoryIdRestorePostParams defines parameters for RestoreMemoryApiV2AgentsAgentIdMemoriesMemoryIdRestorePost.
type RestoreMemoryApiV2AgentsAgentIdMemoriesMemoryIdRestorePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// GetPolicyApiV2AgentsAgentIdPolicyGetParams defines parameters for GetPolicyApiV2AgentsAgentIdPolicyGet.
type GetPolicyApiV2AgentsAgentIdPolicyGetParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// SetPolicyApiV2AgentsAgentIdPolicyPutParams defines parameters for SetPolicyApiV2AgentsAgentIdPolicyPut.
type SetPolicyApiV2AgentsAgentIdPolicyPutParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// ApplyPolicyApiV2AgentsAgentIdPolicyApplyPostParams defines parameters for ApplyPolicyApiV2AgentsAgentIdPolicyApplyPost.
type ApplyPolicyApiV2AgentsAgentIdPolicyApplyPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// ApplyPolicyPresetApiV2AgentsAgentIdPolicyPresetPostParams defines parameters for ApplyPolicyPresetApiV2AgentsAgentIdPolicyPresetPost.
type ApplyPolicyPresetApiV2AgentsAgentIdPolicyPresetPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// ListPolicyPresetsApiV2AgentsAgentIdPolicyPresetsGetParams defines parameters for ListPolicyPresetsApiV2AgentsAgentIdPolicyPresetsGet.
type ListPolicyPresetsApiV2AgentsAgentIdPolicyPresetsGetParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// GetPolicyPresetApiV2AgentsAgentIdPolicyPresetsNameGetParams defines parameters for GetPolicyPresetApiV2AgentsAgentIdPolicyPresetsNameGet.
type GetPolicyPresetApiV2AgentsAgentIdPolicyPresetsNameGetParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// PurgeExpiredMemoriesApiV2AgentsAgentIdPolicyPurgePostParams defines parameters for PurgeExpiredMemoriesApiV2AgentsAgentIdPolicyPurgePost.
type PurgeExpiredMemoriesApiV2AgentsAgentIdPolicyPurgePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// RecallApiV2AgentsAgentIdRecallPostParams defines parameters for RecallApiV2AgentsAgentIdRecallPost.
type RecallApiV2AgentsAgentIdRecallPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// RecallAllApiV2AgentsAgentIdRecallAllPostParams defines parameters for RecallAllApiV2AgentsAgentIdRecallAllPost.
type RecallAllApiV2AgentsAgentIdRecallAllPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// RecallAsOfApiV2AgentsAgentIdRecallAsOfPostParams defines parameters for RecallAsOfApiV2AgentsAgentIdRecallAsOfPost.
type RecallAsOfApiV2AgentsAgentIdRecallAsOfPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// RecallChangedSinceApiV2AgentsAgentIdRecallChangedSincePostParams defines parameters for RecallChangedSinceApiV2AgentsAgentIdRecallChangedSincePost.
type RecallChangedSinceApiV2AgentsAgentIdRecallChangedSincePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// RecallRecentApiV2AgentsAgentIdRecallRecentPostParams defines parameters for RecallRecentApiV2AgentsAgentIdRecallRecentPost.
type RecallRecentApiV2AgentsAgentIdRecallRecentPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// RememberApiV2AgentsAgentIdRememberPostParams defines parameters for RememberApiV2AgentsAgentIdRememberPost.
type RememberApiV2AgentsAgentIdRememberPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// ExtractMemoriesFromConversationApiV2AgentsAgentIdRememberExtractPostParams defines parameters for ExtractMemoriesFromConversationApiV2AgentsAgentIdRememberExtractPost.
type ExtractMemoriesFromConversationApiV2AgentsAgentIdRememberExtractPostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// UploadFileApiV2AgentsAgentIdUploadFilePostParams defines parameters for UploadFileApiV2AgentsAgentIdUploadFilePost.
type UploadFileApiV2AgentsAgentIdUploadFilePostParams struct {
	XSessionToken       *string `json:"x-session-token,omitempty"`
	Authorization       *string `json:"authorization,omitempty"`
	XApiKey             *string `json:"X-Api-Key,omitempty"`
	MemantoSessionToken *string `form:"memanto_session_token,omitempty" json:"memanto_session_token,omitempty"`
}

// GetStatusApiV2StatusGetParams defines parameters for GetStatusApiV2StatusGet.
type GetStatusApiV2StatusGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
	XApiKey       *string `json:"X-Api-Key,omitempty"`
}

// CreateAgentApiV2AgentsPostJSONRequestBody defines body for CreateAgentApiV2AgentsPost for application/json ContentType.
type CreateAgentApiV2AgentsPostJSONRequestBody = AgentCreate

// AnswerApiV2AgentsAgentIdAnswerPostJSONRequestBody defines body for AnswerApiV2AgentsAgentIdAnswerPost for application/json ContentType.
type AnswerApiV2AgentsAgentIdAnswerPostJSONRequestBody = AnswerRequest

// BatchRememberApiV2AgentsAgentIdBatchRememberPostJSONRequestBody defines body for BatchRememberApiV2AgentsAgentIdBatchRememberPost for application/json ContentType.
type BatchRememberApiV2AgentsAgentIdBatchRememberPostJSONRequestBody = BatchRememberRequest

// GenerateConflictReportApiV2AgentsAgentIdConflictsGeneratePostJSONRequestBody defines body for GenerateConflictReportApiV2AgentsAgentIdConflictsGeneratePost for application/json ContentType.
type GenerateConflictReportApiV2AgentsAgentIdConflictsGeneratePostJSONRequestBody = ConflictDetectRequest

// ResolveConflictApiV2AgentsAgentIdConflictsResolvePostJSONRequestBody defines body for ResolveConflictApiV2AgentsAgentIdConflictsResolvePost for application/json ContentType.
type ResolveConflictApiV2AgentsAgentIdConflictsResolvePostJSONRequestBody = ConflictResolveRequest

// GenerateDailySummaryApiV2AgentsAgentIdDailySummaryPostJSONRequestBody defines body for GenerateDailySummaryApiV2AgentsAgentIdDailySummaryPost for application/json ContentType.
type GenerateDailySummaryApiV2AgentsAgentIdDailySummaryPostJSONRequestBody = DailySummaryRequest

// EditMemoryApiV2AgentsAgentIdMemoriesMemoryIdPatchJSONRequestBody defines body for EditMemoryApiV2AgentsAgentIdMemoriesMemoryIdPatch for application/json ContentType.
type EditMemoryApiV2AgentsAgentIdMemoriesMemoryIdPatchJSONRequestBody = MemoryEditRequest

// ExpireMemoryApiV2AgentsAgentIdMemoriesMemoryIdExpirePostJSONRequestBody defines body for ExpireMemoryApiV2AgentsAgentIdMemoriesMemoryIdExpirePost for application/json ContentType.
type ExpireMemoryApiV2AgentsAgentIdMemoriesMemoryIdExpirePostJSONRequestBody = MemoryExpireRequest

// SetPolicyApiV2AgentsAgentIdPolicyPutJSONRequestBody defines body for SetPolicyApiV2AgentsAgentIdPolicyPut for application/json ContentType.
type SetPolicyApiV2AgentsAgentIdPolicyPutJSONRequestBody = MemoryPolicy

// ApplyPolicyApiV2AgentsAgentIdPolicyApplyPostJSONRequestBody defines body for ApplyPolicyApiV2AgentsAgentIdPolicyApplyPost for application/json ContentType.
type ApplyPolicyApiV2AgentsAgentIdPolicyApplyPostJSONRequestBody = PolicyApplyRequest

// ApplyPolicyPresetApiV2AgentsAgentIdPolicyPresetPostJSONRequestBody defines body for ApplyPolicyPresetApiV2AgentsAgentIdPolicyPresetPost for application/json ContentType.
type ApplyPolicyPresetApiV2AgentsAgentIdPolicyPresetPostJSONRequestBody = PolicyPresetRequest

// PurgeExpiredMemoriesApiV2AgentsAgentIdPolicyPurgePostJSONRequestBody defines body for PurgeExpiredMemoriesApiV2AgentsAgentIdPolicyPurgePost for application/json ContentType.
type PurgeExpiredMemoriesApiV2AgentsAgentIdPolicyPurgePostJSONRequestBody = PolicyApplyRequest

// RecallApiV2AgentsAgentIdRecallPostJSONRequestBody defines body for RecallApiV2AgentsAgentIdRecallPost for application/json ContentType.
type RecallApiV2AgentsAgentIdRecallPostJSONRequestBody = RecallRequest

// RecallAllApiV2AgentsAgentIdRecallAllPostJSONRequestBody defines body for RecallAllApiV2AgentsAgentIdRecallAllPost for application/json ContentType.
type RecallAllApiV2AgentsAgentIdRecallAllPostJSONRequestBody = RecallRecentRequest

// RecallAsOfApiV2AgentsAgentIdRecallAsOfPostJSONRequestBody defines body for RecallAsOfApiV2AgentsAgentIdRecallAsOfPost for application/json ContentType.
type RecallAsOfApiV2AgentsAgentIdRecallAsOfPostJSONRequestBody = RecallAsOfRequest

// RecallChangedSinceApiV2AgentsAgentIdRecallChangedSincePostJSONRequestBody defines body for RecallChangedSinceApiV2AgentsAgentIdRecallChangedSincePost for application/json ContentType.
type RecallChangedSinceApiV2AgentsAgentIdRecallChangedSincePostJSONRequestBody = RecallChangedSinceRequest

// RecallRecentApiV2AgentsAgentIdRecallRecentPostJSONRequestBody defines body for RecallRecentApiV2AgentsAgentIdRecallRecentPost for application/json ContentType.
type RecallRecentApiV2AgentsAgentIdRecallRecentPostJSONRequestBody = RecallRecentRequest

// RememberApiV2AgentsAgentIdRememberPostJSONRequestBody defines body for RememberApiV2AgentsAgentIdRememberPost for application/json ContentType.
type RememberApiV2AgentsAgentIdRememberPostJSONRequestBody = RememberRequest

// ExtractMemoriesFromConversationApiV2AgentsAgentIdRememberExtractPostJSONRequestBody defines body for ExtractMemoriesFromConversationApiV2AgentsAgentIdRememberExtractPost for application/json ContentType.
type ExtractMemoriesFromConversationApiV2AgentsAgentIdRememberExtractPostJSONRequestBody = ExtractMemoriesRequest

// UploadFileApiV2AgentsAgentIdUploadFilePostMultipartRequestBody defines body for UploadFileApiV2AgentsAgentIdUploadFilePost for multipart/form-data ContentType.
type UploadFileApiV2AgentsAgentIdUploadFilePostMultipartRequestBody = BodyUploadFileApiV2AgentsAgentIdUploadFilePost

// AsRecallRecentRequestCreatedAfter0 returns the union data inside the RecallRecentRequest_CreatedAfter as a RecallRecentRequestCreatedAfter0
func (t RecallRecentRequest_CreatedAfter) AsRecallRecentRequestCreatedAfter0() (RecallRecentRequestCreatedAfter0, error) {
	var body RecallRecentRequestCreatedAfter0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRecentRequestCreatedAfter0 overwrites any union data inside the RecallRecentRequest_CreatedAfter as the provided RecallRecentRequestCreatedAfter0
func (t *RecallRecentRequest_CreatedAfter) FromRecallRecentRequestCreatedAfter0(v RecallRecentRequestCreatedAfter0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRecentRequestCreatedAfter0 performs a merge with any union data inside the RecallRecentRequest_CreatedAfter, using the provided RecallRecentRequestCreatedAfter0
func (t *RecallRecentRequest_CreatedAfter) MergeRecallRecentRequestCreatedAfter0(v RecallRecentRequestCreatedAfter0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRecallRecentRequestCreatedAfter1 returns the union data inside the RecallRecentRequest_CreatedAfter as a RecallRecentRequestCreatedAfter1
func (t RecallRecentRequest_CreatedAfter) AsRecallRecentRequestCreatedAfter1() (RecallRecentRequestCreatedAfter1, error) {
	var body RecallRecentRequestCreatedAfter1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRecentRequestCreatedAfter1 overwrites any union data inside the RecallRecentRequest_CreatedAfter as the provided RecallRecentRequestCreatedAfter1
func (t *RecallRecentRequest_CreatedAfter) FromRecallRecentRequestCreatedAfter1(v RecallRecentRequestCreatedAfter1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRecentRequestCreatedAfter1 performs a merge with any union data inside the RecallRecentRequest_CreatedAfter, using the provided RecallRecentRequestCreatedAfter1
func (t *RecallRecentRequest_CreatedAfter) MergeRecallRecentRequestCreatedAfter1(v RecallRecentRequestCreatedAfter1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RecallRecentRequest_CreatedAfter) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RecallRecentRequest_CreatedAfter) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRecallRecentRequestCreatedBefore0 returns the union data inside the RecallRecentRequest_CreatedBefore as a RecallRecentRequestCreatedBefore0
func (t RecallRecentRequest_CreatedBefore) AsRecallRecentRequestCreatedBefore0() (RecallRecentRequestCreatedBefore0, error) {
	var body RecallRecentRequestCreatedBefore0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRecentRequestCreatedBefore0 overwrites any union data inside the RecallRecentRequest_CreatedBefore as the provided RecallRecentRequestCreatedBefore0
func (t *RecallRecentRequest_CreatedBefore) FromRecallRecentRequestCreatedBefore0(v RecallRecentRequestCreatedBefore0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRecentRequestCreatedBefore0 performs a merge with any union data inside the RecallRecentRequest_CreatedBefore, using the provided RecallRecentRequestCreatedBefore0
func (t *RecallRecentRequest_CreatedBefore) MergeRecallRecentRequestCreatedBefore0(v RecallRecentRequestCreatedBefore0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRecallRecentRequestCreatedBefore1 returns the union data inside the RecallRecentRequest_CreatedBefore as a RecallRecentRequestCreatedBefore1
func (t RecallRecentRequest_CreatedBefore) AsRecallRecentRequestCreatedBefore1() (RecallRecentRequestCreatedBefore1, error) {
	var body RecallRecentRequestCreatedBefore1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRecentRequestCreatedBefore1 overwrites any union data inside the RecallRecentRequest_CreatedBefore as the provided RecallRecentRequestCreatedBefore1
func (t *RecallRecentRequest_CreatedBefore) FromRecallRecentRequestCreatedBefore1(v RecallRecentRequestCreatedBefore1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRecentRequestCreatedBefore1 performs a merge with any union data inside the RecallRecentRequest_CreatedBefore, using the provided RecallRecentRequestCreatedBefore1
func (t *RecallRecentRequest_CreatedBefore) MergeRecallRecentRequestCreatedBefore1(v RecallRecentRequestCreatedBefore1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RecallRecentRequest_CreatedBefore) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RecallRecentRequest_CreatedBefore) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRecallRequestCreatedAfter0 returns the union data inside the RecallRequest_CreatedAfter as a RecallRequestCreatedAfter0
func (t RecallRequest_CreatedAfter) AsRecallRequestCreatedAfter0() (RecallRequestCreatedAfter0, error) {
	var body RecallRequestCreatedAfter0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRequestCreatedAfter0 overwrites any union data inside the RecallRequest_CreatedAfter as the provided RecallRequestCreatedAfter0
func (t *RecallRequest_CreatedAfter) FromRecallRequestCreatedAfter0(v RecallRequestCreatedAfter0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRequestCreatedAfter0 performs a merge with any union data inside the RecallRequest_CreatedAfter, using the provided RecallRequestCreatedAfter0
func (t *RecallRequest_CreatedAfter) MergeRecallRequestCreatedAfter0(v RecallRequestCreatedAfter0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRecallRequestCreatedAfter1 returns the union data inside the RecallRequest_CreatedAfter as a RecallRequestCreatedAfter1
func (t RecallRequest_CreatedAfter) AsRecallRequestCreatedAfter1() (RecallRequestCreatedAfter1, error) {
	var body RecallRequestCreatedAfter1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRequestCreatedAfter1 overwrites any union data inside the RecallRequest_CreatedAfter as the provided RecallRequestCreatedAfter1
func (t *RecallRequest_CreatedAfter) FromRecallRequestCreatedAfter1(v RecallRequestCreatedAfter1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRequestCreatedAfter1 performs a merge with any union data inside the RecallRequest_CreatedAfter, using the provided RecallRequestCreatedAfter1
func (t *RecallRequest_CreatedAfter) MergeRecallRequestCreatedAfter1(v RecallRequestCreatedAfter1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RecallRequest_CreatedAfter) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RecallRequest_CreatedAfter) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRecallRequestCreatedBefore0 returns the union data inside the RecallRequest_CreatedBefore as a RecallRequestCreatedBefore0
func (t RecallRequest_CreatedBefore) AsRecallRequestCreatedBefore0() (RecallRequestCreatedBefore0, error) {
	var body RecallRequestCreatedBefore0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRequestCreatedBefore0 overwrites any union data inside the RecallRequest_CreatedBefore as the provided RecallRequestCreatedBefore0
func (t *RecallRequest_CreatedBefore) FromRecallRequestCreatedBefore0(v RecallRequestCreatedBefore0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRequestCreatedBefore0 performs a merge with any union data inside the RecallRequest_CreatedBefore, using the provided RecallRequestCreatedBefore0
func (t *RecallRequest_CreatedBefore) MergeRecallRequestCreatedBefore0(v RecallRequestCreatedBefore0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRecallRequestCreatedBefore1 returns the union data inside the RecallRequest_CreatedBefore as a RecallRequestCreatedBefore1
func (t RecallRequest_CreatedBefore) AsRecallRequestCreatedBefore1() (RecallRequestCreatedBefore1, error) {
	var body RecallRequestCreatedBefore1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecallRequestCreatedBefore1 overwrites any union data inside the RecallRequest_CreatedBefore as the provided RecallRequestCreatedBefore1
func (t *RecallRequest_CreatedBefore) FromRecallRequestCreatedBefore1(v RecallRequestCreatedBefore1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecallRequestCreatedBefore1 performs a merge with any union data inside the RecallRequest_CreatedBefore, using the provided RecallRequestCreatedBefore1
func (t *RecallRequest_CreatedBefore) MergeRecallRequestCreatedBefore1(v RecallRequestCreatedBefore1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RecallRequest_CreatedBefore) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RecallRequest_CreatedBefore) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
