#!/usr/bin/env python3
"""Migrate CrewAI unified-memory LanceDB records to a portable OKF bundle.

This adapter targets CrewAI's current ``Memory`` API and its LanceDB storage
schema.  It intentionally omits embedding vectors: vectors are derived data,
are often model-specific, and can be regenerated by the destination system.
Every semantic and provenance field is preserved in YAML frontmatter and is
covered by a canonical SHA-256 fidelity hash.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import tempfile
from collections import Counter
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

ADAPTER_VERSION = "1.0.0"
CREWAI_SCHEMA_COLUMNS = (
    "id",
    "content",
    "scope",
    "categories_str",
    "metadata_str",
    "importance",
    "created_at",
    "last_accessed",
    "source",
    "private",
)
MEMANTO_TYPES = {
    "artifact",
    "commitment",
    "context",
    "decision",
    "error",
    "event",
    "fact",
    "goal",
    "instruction",
    "learning",
    "observation",
    "preference",
    "relationship",
}
TYPE_ALIASES = {
    "failure": "error",
    "incident": "error",
    "insight": "learning",
    "lesson": "learning",
    "output": "artifact",
    "rule": "instruction",
}
SECRET_PATTERNS = (
    re.compile(r"\b(?:sk|ghp|github_pat)-?[A-Za-z0-9_\-]{16,}\b"),
    re.compile(r"(?i)\b(api[_-]?key|password|secret|token)\b\s*[:=]\s*[^\s,;]+"),
)
TABLE_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
ISO_BASIC_OFFSET_RE = re.compile(r"([+-]\d{2})(\d{2})$")
ISO_FRACTION_RE = re.compile(r"[.,](\d+)(?=(?:[+-]\d{2}:\d{2})?$)")


@dataclass(frozen=True)
class CrewAIRecord:
    """Canonical, vector-free representation of one CrewAI memory."""

    id: str
    content: str
    scope: str
    categories: tuple[str, ...]
    metadata: dict[str, Any]
    importance: float
    created_at: str
    last_accessed: str
    source: str | None
    private: bool

    def canonical_dict(self) -> dict[str, Any]:
        """Return every vector-free source field in canonical hash order."""

        return {
            "id": self.id,
            "content": self.content,
            "scope": self.scope,
            "categories": list(self.categories),
            "metadata": self.metadata,
            "importance": self.importance,
            "created_at": self.created_at,
            "last_accessed": self.last_accessed,
            "source": self.source,
            "private": self.private,
        }

    @property
    def sha256(self) -> str:
        """Return the canonical fidelity hash for this source record."""

        return canonical_sha256(self.canonical_dict())


def canonical_json(value: Any) -> str:
    """Return deterministic JSON used by manifests and fidelity checks."""

    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    )


def canonical_sha256(value: Any) -> str:
    """Hash a value after canonical JSON serialization."""

    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def file_sha256(path: Path) -> str:
    """Stream a file into SHA-256 without loading it all into memory."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _parse_json_field(value: Any, expected: type, field: str) -> Any:
    """Decode and type-check a JSON-backed LanceDB column."""

    if value in (None, ""):
        return expected()
    parsed = value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            raise ValueError(f"CrewAI field {field!r} is not valid JSON") from exc
    if not isinstance(parsed, expected):
        raise ValueError(
            f"CrewAI field {field!r} must decode to {expected.__name__}, "
            f"got {type(parsed).__name__}"
        )
    return parsed


def _iso_datetime(value: Any, field: str) -> str:
    """Normalize common ISO-8601 variants to a UTC ``Z`` timestamp."""

    if isinstance(value, datetime):
        parsed = value
    else:
        raw = str(value or "").strip()
        if not raw:
            raise ValueError(f"CrewAI field {field!r} is empty")
        normalized = raw[:-1] + "+00:00" if raw.endswith("Z") else raw
        normalized = ISO_BASIC_OFFSET_RE.sub(r"\1:\2", normalized)
        normalized = ISO_FRACTION_RE.sub(
            lambda match: "." + (match.group(1) + "000000")[:6], normalized
        )
        try:
            parsed = datetime.fromisoformat(normalized)
        except ValueError as exc:
            raise ValueError(
                f"CrewAI field {field!r} is not an ISO-8601 datetime: {raw!r}"
            ) from exc
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def row_to_record(row: dict[str, Any]) -> CrewAIRecord:
    """Validate and normalize one row from CrewAI's LanceDB table."""

    missing = [column for column in CREWAI_SCHEMA_COLUMNS if column not in row]
    if missing:
        raise ValueError(
            "Not a current CrewAI unified-memory table; missing columns: "
            + ", ".join(missing)
        )

    content = str(row["content"] or "").strip()
    record_id = str(row["id"] or "").strip()
    if not content or not record_id:
        raise ValueError("CrewAI records require non-empty id and content fields")

    categories = _parse_json_field(row["categories_str"], list, "categories_str")
    metadata = _parse_json_field(row["metadata_str"], dict, "metadata_str")
    raw_importance = row.get("importance")
    importance = float(0.5 if raw_importance is None else raw_importance)
    if not 0.0 <= importance <= 1.0:
        raise ValueError(f"CrewAI importance must be between 0 and 1: {importance}")

    return CrewAIRecord(
        id=record_id,
        content=content,
        scope=str(row.get("scope") or "/"),
        categories=tuple(str(item) for item in categories),
        metadata=metadata,
        importance=importance,
        created_at=_iso_datetime(row.get("created_at"), "created_at"),
        last_accessed=_iso_datetime(row.get("last_accessed"), "last_accessed"),
        source=str(row["source"]) if row.get("source") else None,
        private=bool(row.get("private", False)),
    )


def read_lancedb_records(
    database: Path,
    *,
    table_name: str = "memories",
    max_records: int = 50_000,
) -> list[CrewAIRecord]:
    """Read CrewAI records without loading vendor-specific embedding vectors."""

    if not database.is_dir():
        raise FileNotFoundError(f"CrewAI LanceDB directory not found: {database}")
    if not TABLE_NAME_RE.fullmatch(table_name):
        raise ValueError(f"Unsafe LanceDB table name: {table_name!r}")
    if not 1 <= max_records <= 50_000:
        raise ValueError("max_records must be between 1 and 50,000")

    try:
        import lancedb
    except ImportError as exc:  # pragma: no cover - exercised by the CLI user
        raise RuntimeError(
            "lancedb is required; run `python -m pip install -r requirements.txt`"
        ) from exc

    database_handle = lancedb.connect(str(database))
    try:
        table = database_handle.open_table(table_name)
    except Exception as exc:
        raise ValueError(
            f"LanceDB table {table_name!r} was not found in {database}"
        ) from exc

    schema_names = set(table.schema.names)
    missing = sorted(set(CREWAI_SCHEMA_COLUMNS) - schema_names)
    if missing:
        raise ValueError(
            "Not a CrewAI unified-memory LanceDB table; missing columns: "
            + ", ".join(missing)
        )

    rows = (
        table.search()
        .select(list(CREWAI_SCHEMA_COLUMNS))
        .limit(max_records + 1)
        .to_list()
    )
    if len(rows) > max_records:
        raise ValueError(
            f"Source has more than {max_records:,} records; raise --max-records "
            "only after reviewing the store size"
        )
    records = [row_to_record(row) for row in rows]
    records.sort(key=lambda record: (record.created_at, record.id))
    return records


def infer_memanto_type(record: CrewAIRecord) -> tuple[str, str]:
    """Map explicit CrewAI categories/metadata to a Memanto memory type."""

    candidates: list[tuple[str, str]] = []
    metadata_type = record.metadata.get("memory_type")
    if metadata_type:
        candidates.append((str(metadata_type), "metadata.memory_type"))
    candidates.extend((category, "category") for category in record.categories)
    candidates.extend(
        (component, "scope")
        for component in record.scope.lower().split("/")
        if component
    )

    for raw, source in candidates:
        normalized = re.sub(r"[^a-z]+", "_", raw.lower()).strip("_")
        normalized = TYPE_ALIASES.get(normalized, normalized)
        if normalized in MEMANTO_TYPES:
            return normalized, source
    return "observation", "fallback"


def _slug(value: str, *, fallback: str = "memory", limit: int = 54) -> str:
    """Create a bounded, filesystem-safe slug."""

    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return (slug or fallback)[:limit].rstrip("-")


def _title(record: CrewAIRecord) -> str:
    """Choose a concise human-readable title for an OKF memory."""

    metadata_title = record.metadata.get("title")
    if isinstance(metadata_title, str) and metadata_title.strip():
        raw = metadata_title.strip()
    else:
        raw = re.split(r"(?<=[.!?])\s+|\n", record.content, maxsplit=1)[0]
    return re.sub(r"\s+", " ", raw).strip()[:100]


def _tag(value: str) -> str:
    """Normalize a value into one bounded Memanto tag."""

    normalized = re.sub(r"[^a-z0-9._-]+", "-", value.lower()).strip("-")
    return normalized[:64].rstrip("-")


def record_tags(record: CrewAIRecord) -> list[str]:
    """Build stable, bounded, de-duplicated tags from CrewAI fields."""

    values = ["crewai", *record.categories]
    values.extend(f"scope-{part}" for part in record.scope.split("/") if part)
    if record.private:
        values.append("visibility-private")
    result: list[str] = []
    for value in values:
        normalized = _tag(str(value))
        if normalized and normalized not in result:
            result.append(normalized)
    return result[:20]


def redact_secrets(value: Any) -> tuple[Any, int]:
    """Recursively redact common credentials when explicitly requested."""

    if isinstance(value, str):
        count = 0
        redacted = value
        for pattern in SECRET_PATTERNS:
            redacted, matches = pattern.subn("[REDACTED]", redacted)
            count += matches
        return redacted, count
    if isinstance(value, list):
        output = []
        total = 0
        for item in value:
            clean, count = redact_secrets(item)
            output.append(clean)
            total += count
        return output, total
    if isinstance(value, dict):
        output_dict: dict[str, Any] = {}
        total = 0
        for key, item in value.items():
            clean, count = redact_secrets(item)
            output_dict[str(key)] = clean
            total += count
        return output_dict, total
    return value, 0


def _render_document(
    record: CrewAIRecord,
    *,
    memory_type: str,
    mapping_basis: str,
    content: str,
    metadata: dict[str, Any],
    redactions: int,
) -> str:
    """Render one vector-free CrewAI record as an OKF Markdown document."""

    source_uri = f"crewai://unified-memory/{record.id}"
    crewai_extension = {
        "schema": "unified-memory-lancedb",
        "id": record.id,
        "scope": record.scope,
        "categories": list(record.categories),
        "metadata": metadata,
        "importance": record.importance,
        "last_accessed": record.last_accessed,
        "source": record.source,
        "private": record.private,
        "mapping_basis": mapping_basis,
        "embedding": "omitted-derived-data",
    }
    frontmatter = {
        "type": memory_type,
        "title": _title(record),
        "description": "Migrated from CrewAI unified memory (LanceDB).",
        "resource": source_uri,
        "tags": record_tags(record),
        "timestamp": record.created_at,
        "x_memanto": {
            "type": memory_type,
            "confidence": record.importance,
            "source": "crewai",
        },
        "crewai": crewai_extension,
        "source_record_sha256": record.sha256,
        "redactions": redactions,
    }
    rendered = yaml.safe_dump(
        frontmatter,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    ).strip()
    return f"---\n{rendered}\n---\n\n{content.strip()}\n"


def _render_index(title: str, links: Iterable[tuple[str, str]]) -> str:
    """Render an OKF navigation index."""

    lines = ["---", "type: index", f"title: {json.dumps(title)}", "---", ""]
    lines.extend(f"- [{label}]({target})" for label, target in links)
    return "\n".join(lines) + "\n"


def safe_destructive_target(path: Path, *, purpose: str) -> Path:
    """Reject broad paths before a generated directory can be replaced."""

    target = path.resolve()
    forbidden = {
        Path(target.anchor).resolve(),
        Path.home().resolve(),
        Path.cwd().resolve(),
    }
    if target in forbidden or len(target.parts) < 3:
        raise ValueError(f"Refusing unsafe {purpose}: {target}")
    return target


def _publish_directory_atomically(temp_root: Path, output: Path) -> None:
    """Publish a directory while preserving the previous bundle on failure."""

    previous: Path | None = None
    if output.exists():
        previous = Path(
            tempfile.mkdtemp(prefix=f".{output.name}-previous-", dir=output.parent)
        )
        previous.rmdir()
        os.replace(output, previous)

    try:
        os.replace(temp_root, output)
    except Exception:
        if previous is not None and previous.exists() and not output.exists():
            os.replace(previous, output)
        raise
    else:
        if previous is not None:
            shutil.rmtree(previous)


def write_okf_bundle(
    records: list[CrewAIRecord],
    output: Path,
    *,
    source_database: Path,
    table_name: str = "memories",
    include_private: bool = False,
    redact: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    """Write a deterministic, atomic OKF bundle and return its manifest."""

    output = safe_destructive_target(output, purpose="output directory")
    if output.exists() and not force:
        raise FileExistsError(f"Output already exists (use --force): {output}")

    selected = [record for record in records if include_private or not record.private]
    skipped_private = len(records) - len(selected)
    if not selected:
        raise ValueError("No records selected for migration")

    output.parent.mkdir(parents=True, exist_ok=True)
    temp_root = Path(tempfile.mkdtemp(prefix=f".{output.name}-", dir=output.parent))
    manifest_records: list[dict[str, Any]] = []
    per_type: Counter[str] = Counter()
    total_redactions = 0
    type_links: dict[str, list[tuple[str, str]]] = {}

    try:
        memories_dir = temp_root / "memories"
        memories_dir.mkdir()
        used_paths: set[str] = set()

        for record in selected:
            memory_type, mapping_basis = infer_memanto_type(record)
            content: Any = record.content
            metadata: Any = record.metadata
            redactions = 0
            if redact:
                content, content_redactions = redact_secrets(content)
                metadata, metadata_redactions = redact_secrets(metadata)
                redactions = content_redactions + metadata_redactions
            total_redactions += redactions

            type_dir = memories_dir / memory_type
            type_dir.mkdir(exist_ok=True)
            suffix = _slug(record.id, fallback=record.sha256[:12], limit=20)
            stem = f"{_slug(_title(record))}-{suffix}"
            relative = f"memories/{memory_type}/{stem}.md"
            if relative in used_paths:
                relative = f"memories/{memory_type}/{stem}-{record.sha256[:8]}.md"
            used_paths.add(relative)
            destination = temp_root / relative
            destination.write_text(
                _render_document(
                    record,
                    memory_type=memory_type,
                    mapping_basis=mapping_basis,
                    content=str(content),
                    metadata=metadata,
                    redactions=redactions,
                ),
                encoding="utf-8",
                newline="\n",
            )
            per_type[memory_type] += 1
            type_links.setdefault(memory_type, []).append(
                (_title(record), destination.name)
            )
            manifest_records.append(
                {
                    "crewai_id": record.id,
                    "source_record_sha256": record.sha256,
                    "okf_path": relative,
                    "okf_file_sha256": file_sha256(destination),
                    "memanto_type": memory_type,
                    "mapping_basis": mapping_basis,
                    "private": record.private,
                    "redactions": redactions,
                }
            )

        for memory_type, links in sorted(type_links.items()):
            type_index = memories_dir / memory_type / "index.md"
            type_index.write_text(
                _render_index(f"CrewAI {memory_type} memories", sorted(links)),
                encoding="utf-8",
                newline="\n",
            )

        memory_type_links = [
            (f"{memory_type} ({count})", f"{memory_type}/index.md")
            for memory_type, count in sorted(per_type.items())
        ]
        (memories_dir / "index.md").write_text(
            _render_index("CrewAI unified memories", memory_type_links),
            encoding="utf-8",
            newline="\n",
        )
        (temp_root / "index.md").write_text(
            _render_index(
                "CrewAI to Memanto OKF bundle", [("Memories", "memories/index.md")]
            ),
            encoding="utf-8",
            newline="\n",
        )

        manifest: dict[str, Any] = {
            "adapter": "crewai-unified-memory-to-okf",
            "adapter_version": ADAPTER_VERSION,
            "created_at": max(record.created_at for record in records),
            "source": {
                "framework": "CrewAI",
                "storage": "LanceDB",
                "schema": "unified-memory",
                "database": source_database.name,
                "table": table_name,
                "total_records": len(records),
                "canonical_sha256": canonical_sha256(
                    [record.canonical_dict() for record in records]
                ),
            },
            "migration": {
                "selected_records": len(selected),
                "mapped_records": len(manifest_records),
                "skipped_private": skipped_private,
                "redactions": total_redactions,
                "per_type": dict(sorted(per_type.items())),
                "embedding_policy": "omitted-derived-data",
            },
            "records": manifest_records,
        }
        manifest_path = temp_root / "migration-manifest.json"
        manifest_path.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
            newline="\n",
        )

        summary_lines = [
            "# CrewAI unified memory migration summary",
            "",
            f"- Source records: **{len(records)}**",
            f"- Mapped OKF memories: **{len(manifest_records)}**",
            f"- Private records skipped: **{skipped_private}**",
            f"- Explicit secret redactions: **{total_redactions}**",
            "- Embeddings: omitted (derived, model-specific data)",
            "",
            "| Memanto type | Count |",
            "|---|---:|",
        ]
        summary_lines.extend(
            f"| `{memory_type}` | {count} |"
            for memory_type, count in sorted(per_type.items())
        )
        (temp_root / "MIGRATION_SUMMARY.md").write_text(
            "\n".join(summary_lines) + "\n", encoding="utf-8", newline="\n"
        )

        _publish_directory_atomically(temp_root, output)
        return manifest
    except Exception:
        shutil.rmtree(temp_root, ignore_errors=True)
        raise


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser for the migration adapter."""

    parser = argparse.ArgumentParser(
        description="Migrate current CrewAI unified-memory LanceDB records to OKF"
    )
    parser.add_argument("source", type=Path, help="CrewAI LanceDB directory")
    parser.add_argument("output", type=Path, help="Destination OKF bundle directory")
    parser.add_argument("--table", default="memories", help="LanceDB table name")
    parser.add_argument(
        "--max-records",
        type=int,
        default=50_000,
        help="Maximum records to read, between 1 and 50,000",
    )
    parser.add_argument(
        "--include-private",
        action="store_true",
        help="Include CrewAI private memories (excluded by default)",
    )
    parser.add_argument(
        "--redact-secrets",
        action="store_true",
        help="Redact common credentials from content and metadata",
    )
    parser.add_argument("--force", action="store_true", help="Replace output")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the adapter CLI and print its migration summary."""

    args = build_parser().parse_args(argv)
    records = read_lancedb_records(
        args.source, table_name=args.table, max_records=args.max_records
    )
    manifest = write_okf_bundle(
        records,
        args.output,
        source_database=args.source,
        table_name=args.table,
        include_private=args.include_private,
        redact=args.redact_secrets,
        force=args.force,
    )
    migration = manifest["migration"]
    print(
        "CrewAI unified memory -> OKF: "
        f"{migration['mapped_records']}/{manifest['source']['total_records']} mapped, "
        f"{migration['skipped_private']} private skipped, "
        f"{migration['redactions']} redactions"
    )
    print(f"Bundle: {args.output.resolve()}")
    print(f"Source SHA-256: {manifest['source']['canonical_sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
