"""Bind LLM-generated conflict references to authoritative memory objects.

Conflict reports are generated by an LLM, so their object identifiers and
human-readable summaries are untrusted.  This module turns those references
into a fail-closed, server-verified binding before destructive resolution is
allowed.
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any

from memanto.app.services.memory_read_service import MemoryReadService

_SESSION_MEMORY_ID_RE = re.compile(r"^- \*\*Memory ID\*\*: `([^`]+)`\s*$", re.MULTILINE)


def extract_recent_memory_ids(session_text: str) -> set[str]:
    """Return memory IDs that were actually logged in the recent session text."""
    if not isinstance(session_text, str) or not session_text:
        return set()
    return {match.group(1).strip() for match in _SESSION_MEMORY_ID_RE.finditer(session_text)}


def _fingerprint(memory: dict[str, Any]) -> str:
    """Create a stable digest for the security-relevant memory identity/content."""
    payload = {
        "id": memory.get("id"),
        "title": memory.get("title"),
        "content": memory.get("content"),
        "type": memory.get("type"),
        "created_at": memory.get("created_at"),
    }
    encoded = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _load_authoritative_memory(
    reader: MemoryReadService, memory_id: Any, namespace: str
) -> dict[str, Any] | None:
    if not isinstance(memory_id, str) or not memory_id.strip():
        return None
    return reader.get_memory(memory_id.strip(), namespace)


def bind_conflict_references(
    conflicts: list[dict[str, Any]],
    *,
    client: Any,
    namespace: str,
    recent_memory_ids: set[str],
) -> list[dict[str, Any]]:
    """Replace model-authored display data with authoritative memory data.

    A destructive conflict is bindable only when both referenced memories
    exist in the agent namespace and the ``new_memory_id`` was actually logged
    in the recent session content being analyzed.  The model therefore cannot
    invent an unrelated new object reference and pair it with spoofed display
    text.
    """
    reader = MemoryReadService(client)
    bound: list[dict[str, Any]] = []

    for original in conflicts:
        item = dict(original)
        old_id = item.get("old_memory_id")
        new_id = item.get("new_memory_id")

        reason: str | None = None
        if not isinstance(old_id, str) or not old_id.strip():
            reason = "missing_old_memory_id"
        elif not isinstance(new_id, str) or not new_id.strip():
            reason = "missing_new_memory_id"
        elif old_id == new_id:
            reason = "same_memory_id"
        elif new_id not in recent_memory_ids:
            reason = "new_memory_not_in_recent_session"

        old_memory = _load_authoritative_memory(reader, old_id, namespace)
        new_memory = _load_authoritative_memory(reader, new_id, namespace)

        if old_memory is None and reason is None:
            reason = "old_memory_not_found_in_agent_namespace"
        if new_memory is None and reason is None:
            reason = "new_memory_not_found_in_agent_namespace"

        # Never trust LLM-authored summaries for the objects a user may delete.
        if old_memory is not None:
            item["old_content"] = old_memory.get("content")
            item["old_title"] = old_memory.get("title")
        if new_memory is not None:
            item["new_content"] = new_memory.get("content")
            item["new_title"] = new_memory.get("title")

        if reason is not None:
            item["_reference_binding"] = {"status": "blocked", "reason": reason}
            bound.append(item)
            continue

        assert old_memory is not None and new_memory is not None
        item["_reference_binding"] = {
            "status": "bound",
            "old_memory_id": old_id,
            "new_memory_id": new_id,
            "old_fingerprint": _fingerprint(old_memory),
            "new_fingerprint": _fingerprint(new_memory),
        }
        bound.append(item)

    return bound


def validate_conflict_reference_binding(
    conflict: dict[str, Any], *, client: Any, namespace: str
) -> None:
    """Fail closed unless conflict IDs still match their authoritative binding."""
    binding = conflict.get("_reference_binding")
    if not isinstance(binding, dict) or binding.get("status") != "bound":
        raise ValueError(
            "Conflict references are not server-verified; regenerate the conflict report before destructive resolution"
        )

    old_id = conflict.get("old_memory_id")
    new_id = conflict.get("new_memory_id")
    if old_id != binding.get("old_memory_id") or new_id != binding.get("new_memory_id"):
        raise ValueError("Conflict memory references changed after validation")

    reader = MemoryReadService(client)
    old_memory = _load_authoritative_memory(reader, old_id, namespace)
    new_memory = _load_authoritative_memory(reader, new_id, namespace)
    if old_memory is None or new_memory is None:
        raise ValueError("A conflict memory no longer exists in the agent namespace")

    if _fingerprint(old_memory) != binding.get("old_fingerprint"):
        raise ValueError("Old conflict memory changed after report generation")
    if _fingerprint(new_memory) != binding.get("new_fingerprint"):
        raise ValueError("New conflict memory changed after report generation")
